name: Python Check Format

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull baseline for HybridQ
        run: |
          docker pull smandra/hybridq-baseline:latest
          docker tag smandra/hybridq-baseline:latest hybridq-baseline:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg SKIP_PRE_CACHING=true --build-arg HYBRIDQ_DISABLE_CPP_CORE=true hybridq

      - name: Check format
        run: |
          docker run --rm hybridq -c 'pip install yapf==0.31.0 clang-format==9.0.0 && \
            cd /opt/hybridq && \
            bash scripts/check_format.sh'
