name: Python (cp38-cp38) PyTest - simulation_2

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg ARCH=x86-64 \
                               --build-arg BASELINE=docker.io/smandra/hybridq-baseline:cp38-cp38 \
                               hybridq

      - name: Run tests
        run: |
          docker run --rm hybridq bash -c 'python -m pip install pytest-random-order && \
            python -m pytest -sv --random-order -k 'simulation_2__' /opt/hybridq/tests/tests.py'
